// build.cjs — precompile JSX -> plain JS so the site needs no in-browser Babel.
//
//   npm install --no-save @babel/standalone@7   (one-time, node_modules gitignored)
//   node build.cjs
//
// Source files stay as .jsx (the things you edit). This emits a .js next to each
// one (classic React.createElement transform — React is a UMD global, no imports).
// After editing any .jsx, re-run `node build.cjs` and bump the ?v= in index.html.
const fs = require('fs');
const path = require('path');
const Babel = require('@babel/standalone');

const files = [];
for (const dir of ['components', 'pages']) {
  for (const f of fs.readdirSync(dir)) {
    if (f.endsWith('.jsx')) files.push(path.join(dir, f));
  }
}
files.push('app.jsx');

let ok = 0;
for (const src of files) {
  const code = fs.readFileSync(src, 'utf8');
  // preset-react only: transform JSX/fragments, leave modern JS (arrow fns,
  // spread, optional chaining) untouched for evergreen browsers.
  const out = Babel.transform(code, { presets: [['react']] }).code;
  const dest = src.replace(/\.jsx$/, '.js');
  fs.writeFileSync(dest, out + '\n');
  ok++;
  console.log('  ✓', src, '->', dest);
}
console.log(`compiled ${ok} files`);

// ---------------------------------------------------------------------------
// Per-route HTML + sitemap, generated from components/Routes.jsx.
//
// Every route is served its own HTML file (golf.html → /golf via cleanUrls in
// vercel.json) carrying that page's title, description, canonical and og:* in
// the raw HTML. Without this, every URL served index.html with the HOME page's
// canonical, and only JavaScript corrected it — Google advises against JS
// changing a canonical away from the one in the served HTML, and treats the
// pages as duplicates of the home page.
//
// index.html stays the hand-edited source; the generated .html files are
// committed (the client mirror repo has no build step) and rebuilt on every
// Vercel deploy, so they cannot drift. Never edit them by hand.
const vm = require('vm');
const ORIGIN = 'https://www.dutchmanspipeclub.com';

const routeBox = { window: {} };
vm.runInNewContext(fs.readFileSync('components/Routes.jsx', 'utf8'), routeBox);
const routes = routeBox.window.DP_ROUTES;
if (!Array.isArray(routes) || !routes.length) throw new Error('DP_ROUTES not found in components/Routes.jsx');

const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

// Replace exactly one occurrence, or fail the build. A silent miss would ship a
// page with the home canonical — the very bug this exists to prevent.
function swap(html, re, value, label) {
  const hits = html.match(new RegExp(re.source, 'g')) || [];
  if (hits.length !== 1) throw new Error(`index.html: expected 1 ${label}, found ${hits.length}`);
  return html.replace(re, value);
}

// "Golf | Jack Nicklaus Signature Course — Dutchman's Pipe Club" -> "Golf"
const shortName = (r) => (r.id === 'home' ? 'Home' : r.title.split(/\s[|—]\s/)[0]);

const source = fs.readFileSync('index.html', 'utf8');
const fallbackRe = /<div id="app">[\s\S]*?\n  <\/div>/;
const fallback = (source.match(fallbackRe) || [])[0];
if (!fallback) throw new Error('index.html: no-JS fallback <div id="app"> not found');
// The home fallback's per-section paragraphs, keyed by their <h2>, and its
// address/telephone paragraph, reused so each page's fallback stays accurate.
const sections = {};
fallback.replace(/<h2>([^<]+)<\/h2>\s*(<p>[\s\S]*?<\/p>)/g, (_, h, p) => { sections[h.trim()] = p; });
const contact = (fallback.match(/<p>An invitation-only[\s\S]*?<\/p>/) || [])[0] || '';
const navRe = /\n    <nav aria-label="Pages">[\s\S]*?<\/nav>/;
const nav = (fallback.match(navRe) || [])[0] || '';

let pages = 0;
for (const r of routes) {
  if (r.id === 'home') continue;
  const url = ORIGIN + r.path;
  const title = esc(r.title);
  const robots = r.noindex ? 'noindex,nofollow' : 'index,follow,max-image-preview:large,max-snippet:-1';
  let html = source;
  html = html.replace('<!doctype html>', '<!doctype html>\n<!-- GENERATED by build.cjs from index.html + components/Routes.jsx. Do not edit; edit those and rebuild. -->');
  html = swap(html, /<title>[^<]*<\/title>/, `<title>${title}</title>`, '<title>');
  html = swap(html, /<link rel="canonical" href="[^"]*">/, `<link rel="canonical" href="${url}">`, 'canonical');
  html = swap(html, /<meta name="robots" content="[^"]*">/, `<meta name="robots" content="${robots}">`, 'robots meta');
  html = swap(html, /<meta property="og:url" content="[^"]*">/, `<meta property="og:url" content="${url}">`, 'og:url');
  html = swap(html, /<meta property="og:title" content="[^"]*">/, `<meta property="og:title" content="${title}">`, 'og:title');
  html = swap(html, /<meta name="twitter:title" content="[^"]*">/, `<meta name="twitter:title" content="${title}">`, 'twitter:title');
  if (r.description) {
    const d = esc(r.description);
    html = swap(html, /<meta name="description" content="[^"]*">/, `<meta name="description" content="${d}">`, 'description');
    html = swap(html, /<meta property="og:description" content="[^"]*">/, `<meta property="og:description" content="${d}">`, 'og:description');
    html = swap(html, /<meta name="twitter:description" content="[^"]*">/, `<meta name="twitter:description" content="${d}">`, 'twitter:description');
  }
  // The home hero preload is wasted bandwidth on every other page.
  html = html.replace(/\n  <!-- LCP: the home hero[^\n]*\n  <link rel="preload" as="image" href="assets\/home-hero\.jpg"[^>]*>/, '');

  // No-JS fallback for this page: its own heading, the matching section from
  // the home fallback (or the route description when there is none), the
  // club's contact line, and the page links.
  const name = shortName(r);
  const sectionKey = { racquets: 'Racquet Sports' }[r.id] || name;
  const body = [
    `<h1>${esc(name)} — Dutchman's Pipe Club</h1>`,
    sections[sectionKey] || (r.description ? `<p>${esc(r.description)}</p>` : ''),
    contact,
  ].filter(Boolean).map((l) => '    ' + l).join('\n\n');
  html = html.replace(fallbackRe, `<div id="app">\n${body}\n${nav}\n  </div>`);

  fs.writeFileSync(r.id + '.html', html);
  pages++;
  console.log('  ✓', r.path, '->', r.id + '.html');
}

// Sitemap: every indexable route.
const sitemap = ['<?xml version="1.0" encoding="UTF-8"?>', '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
  .concat(routes.filter((r) => !r.noindex).map((r) => [
    '  <url>',
    `    <loc>${ORIGIN + r.path}</loc>`,
    `    <changefreq>${r.id === 'home' ? 'weekly' : 'monthly'}</changefreq>`,
    `    <priority>${r.id === 'home' ? '1.0' : '0.8'}</priority>`,
    '  </url>',
  ].join('\n')))
  .concat(['</urlset>', '']).join('\n');
fs.writeFileSync('sitemap.xml', sitemap);
console.log(`generated ${pages} route pages + sitemap.xml`);
